name: Node.js CI  

on: [push]  

jobs:  
  build:  
    runs-on: ubuntu-latest  # 使用GitHub托管的Runner  
    # 如果使用自托管Runner，可以指定为self-hosted  
    # runs-on: [self-hosted, Linux, X64]  

    steps:  
    - name: test  
      run: echo 'hi'
